Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: code.EmpleadosFunction
      CodeUri: C:\Users\AlumnoFP\IdeaProjects\LambdaExamen2Eval
      Runtime: java17
      Architectures:
        - x86_64